name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    stragety:
      matrix:
        node-version: [16]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Deploy
      run: npm run deploy

    - name: Get GitHub API token
      run: echo "::set-env name=GITHUB_TOKEN::${{ secrets.GITHUB_TOKEN }}"