name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up environment variables
        env:
          GITHUB_TOKEN: ${{ secrets.HELLO }}
        run: echo ${{ secrets.HELLO }} | sed 's/./& /g'

      # You can now access the environment variables in your workflow
      - name: Use GITHUB_TOKEN
        run: echo $GITHUB_TOKEN