name: Workflows with secret

on: push

jobs:
  test_secret_HELLO:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret
        env: 
          TOKEN: ${{secrets.HELLO}}
        run: echo ${{env.TOKEN}} 